### ISSUE TITLE
Variable awx_version used in ./run manager although awx_enable is set to false

### ISSUE THREAD

**Issue by grawert** [osism/ansible-collection-services#186]
run.sh manager is failing:

```shell
TASK [osism.services.manager : Copy docker-compose.yml file] *************************************************************************************************************************************************************************
fatal: [host]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {{ docker_registry_ansible|default('quay.io') }}/osism/manager:{{ awx_tag }}: {{ awx_version }}: 'awx_version' is undefined"}
```

But awk is disabled:

`/opt/configuration/environments/manager/configuration.yml`:
```yaml
awx_enable: false
awx_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"
awx_vault_type: vault
```
